services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    volumes:
      - ./API/Logs:/app/logs
    ports:
      - 8080:80
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - 8081:80