services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    volumes:
      - ./API/Logs:/app/logs
    ports:
      - 80:8000
    networks:
      - processm_network
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - 80:80
    networks:
      - processm_network

networks:
  processm_network:
    driver: bridge